interface CategoryDescriptions {
  [key: string]: string | null;
}

export const categoryDescriptions: CategoryDescriptions = {
  "ik-blue":
    "International Klein Blue is dark ultramarine blue color, well-known due to French artist Yves Klein. The intensive color become very popular not only in graphic design, but also in fashion.",
  letterspace:
    "Words divided into individual letters or syllables and arranged randomly. The trend is very popular especially in the last two years.",
  "left-right-up-down":
    "This typography trend consists of placing words on the sides of the format. Composition seems so avant-garde, but it has one major disadvantage. It forced people to read in four different directions, which can be fun, but not everytime.",
  scanned:
    "Distorted typography is achieved by using a scanner. Experimental output guaranteed.",
  staircase:
    "Diagonal arrangement of typography reminding the stairs, goings up or down across the format.",
  frame:
    "The frame is used as an additional element that helps to highlight the inner content. In many cases it is accompanied by other trends as underlined and central aligned typography.",
  stretched: null,
  repetition: null,
  "neon-colors":
    "Bright, vivid, reflective, eye-catching colors are very popular. These colors are often used when screen printing. It provokes and has powerful impact on eyes.",
  slash:
    "Maybe the most trendy shape ever. Slash appears as a diagonal stroke from one corner to the opposite. It goes across the whole bookcover or poster, more often from left to right.",
  flash:
    "The letter, logo or any different kind of additional information placed in a circle. Design is not usually built on this element directly, but is integral to it.",
  underlined:
    "Underlined typography works very effectively and also very efficiently. Words and whole sentences are usually underlined without any purpose, but it might attract the attention of the audience and communicate the message. This form is widely spread around the whole world.",
  gradients:
    "Adobe Illustrator offers many possibilities and various gradient spectrums is one of them. These designs are easilly and fast generated by the computer and clients pay for it because it looks fancy. But seriously, this form is simply able to catch the attention even when there is no reason to use it (maybe because of its rare ocurence in the nature.)",
  wiggles: null,
  "type-on-path": null,
  randomized: null,
  "center-aligned":
    "Massive simple typography aligned in the center of format. The most commonly used in one color. This trend may have its roots in graphic design from the early 20th century, or may also be meant as irony and the desire for liberation from the well-ordered Swiss typography.",
  "text-on-cover": null,
  hyphens:
    "Words divided in two or more lines. Sometimes the words are divided because of filling format, but sometimes it is used quite illogically, without any particular reason.",
  "blank-cover":
    "Usually bookcovers with simple typography and lots of empty space.",
  "table-of-contents":
    "Name index, table of contents or bulletpoints are located directly on the cover of book/magazine. It gives the impression of a conceptual approach.",
  slant:
    "Format is divided into two parts with different colors. Usually exactly half and half from one corner to another.",
  "various-formats":
    "One book is complied from different sizes of pages and various types of paper. Sometimes is separates whole printed matter to independent parts like chapters for example. This form is sometimes so overused, that book or catalog that has lost its function and there is no way not browse it easily.",
  outlined: null,
  "exposed-content":
    "One of the most popular current trends, usually seen on book and magazine covers, where images are located in different compositions and reveal the inner content. This kind of design goes very well together with visuals for the art exhibitions where all the artworks are indexed on one poster. Typography is usually placed over this layer.",
  "3-d": null,
  highlighted:
    "Inspiration for these forms probably comes right from graphic design programs and text editors. Otherwise quite boring and dull typography suddenly gets the right contemporary appearance.",
  strikethrough:
    "The one of the basic typography style features in each graphic editor that became surely a trend. The striketrough sentences or the censored words started to appear in contemporary graphic design in a bigger scale.",
  "diagonal-pattern":
    "Lines going usually at 45 degrees angle. Inspiritation comes from the stripes used on caution places signboards. Eye-catching, strong expression, always works great when you need to fill the white space.",
  rhombus:
    "In some Central European countries rhombus is considered as a simplified symbol for the vagina. For this reason, designers in these countries do not use it very often, even if they wanted. Despite this, it surely belongs to the current trends in graphic design.",
  "mickey-hands": null,
  "ancient-statues": null,
  "infinity-shapes":
    "This is how it looks when geometry and mathematics influeced graphic designers. Escher-like logical nonsences are mixed with the other graphic design trends, for example night sky backgrounds or center aligned typography.",
  stars:
    "The fascination with the sky during the night returned and seems to be one of the contemporary trends. Often with infinity shapes, triangles or thin lines aligned in the central composition. It is interesting that this trend is mostly associated with music.",
  "still-life":
    "Everything placed on the pile and photographed. The instant way how to create trendy looking poster.",
  diamonds:
    "Diamonds are beautiful stones. The shape of the crystal and its triangulary polygonal look made one of the iconic symbols in graphic design today.",
  "virtual-space-reality": null,
};
